== Websocket binding used for Kafka-REST

Assume the version of the Websocket binding and the use of optional features has been negotiated during 
the handshake phase after the socket is open. This Websocket binding is characterized by the following rules.

- Each request contains the method, path, and optional type and data.
- Each request may be sent with a unique-ID for the client to correlate its response to the request.
- Arbitrary Http headers in the request are not supported.
- The content-type header can be optionally supplied if the content is present.
- The accept header can be optionally supplied if the response is expected.
- The content entity can be optionall supplied.
- The server can periodically send a heartbeat message to the connected clients to keep the connections alive.

REST over Websocket uses the following message format.

[caption="Format: "]
.General Syntax
====
{"id": "*_identifier_*", "method": "*_method_*", "path": "*_path_*", 
 "type": "*_type_header_*", "accept": "*_accept_header_*",
 "data": *_content_*}
====
where

      - *_identifier_* represents an identifier for the request message which is used in any response message to refer to the original request message,

      - *_method_* represents the request method,

      - *_path_* represents the request path,

      - *_type_header_* and *_accept_header_* represent the optional content-type and accept headers,

      - *_content_* represents the optional content entity.



In the following sections, the messages used by the websocket binding of kafka-rest operations are described. All the operations supported by kafka-rest can be invoked over Websocket using this websocket binding.
In addition to those operations, there are subscribe operations that are specifically included for this websocket binding.

For details about all the operations supported by kafka-rest, please refer to kafka-rest's documentation [1].

==== Get the list of topics

[caption="Format: "]
.list
====
{"id": "*_identifier_*", "method": "GET", "path": "/topics"}
====

.Sample Request (listing topics)
----
{"id": "123", "method": "GET", "path": "/topics"}
----

.Sample Response
----
{"id": "123", "data": ["test", "jsontest"]}
----

==== Get the information about a specific topic

[caption="Format:"]
.getTopic
====
{"id": "*_identifier_*", "method": "GET", "path": "/topics/*_topic_*"}
====
where *_topic_* is a topic name.

.Sample Request (getting information about topic "test")
----
{"id": "124", "method": "GET", "path": "/topics/test"}
----

Sample Response
----
{"id": "124", "data": {"name":"test","configs":{},"partitions":[{"partition":0,"leader":0,"replicas":[{"broker":0,"leader":true,"in_sync":true}]}]}}
----

==== Produce and consume messages in Binary Mode

===== Producing messages (Binary Mode)

[caption="Format: "]
.produceBinary
====
{"id": "*_identifier_*", "method": "POST", "path": "/topics/*_topic_*", "type": "application/vnd.kafka.binary.v1+json",  "data": {"records": [{"value": "*_base64_message_*"}]}}
====
where *_topic_* is a topic name and *_base64_message_* is a base64 encoded string representing the content entity.

.Sample Request (publishing binary message "Kafka" to topic "test")
----
{"id": "125", "method": "POST", "path": "/topics/test", "type": "application/vnd.kafka.binary.v1+json",  "data": {"records": [{"value": "S2Fma2E="}]}}
----

.Sample Response
----
{"id": "125", "data": {"offsets":[{"partition":0,"offset":1,"error_code":null,"error":null}],"key_schema_id":null,"value_schema_id":null}}
----

===== Consuming Messages (Binary-Mode)

     - 1. Create a consumer (Binary-Mode)

[caption="Format: "]
.createGroup
====
{"id": "*_identifier_*", "method": "POST", "path": "/consumers/*_consumer_group_*", "type": "application/vnd.kafka.binary.v1+json", "data": {"id": "*_instance_name_*", "format": "binary", "auto.offset.reset": "smallest"}}
====
where *_consumer_group_* is a consumer group name and *_instance_name_* is a consumer instance name.

.Sample Request (creating binary consumer "my_instance" at consumer group "my_consumer_group")
----
{"id": "126", "method": "POST", "path": "/consumers/my_consumer_group", "type": "application/vnd.kafka.binary.v1+json",  "data": {"id": "my_instance", "format": "binary", "auto.offset.reset": "smallest"}}
----

.Sample Response
----
{"id": "126", "data": {"instance_id":"my_instance","base_uri":"http://localhost:8082/consumers/my_consumer_group/instances/my_instance"}}
----

     - 2. Subscribe to the topic (Binary-Mode)

[caption="Format: "]
.subscribeTopicBinary
====
{"id": "*_identifier_*", "method": "GET", "path": "/ws/consumers/*_consumer_group_*/instances/*_instance_name_*/topics/*_topic_*", "accept": "application/vnd.kafka.binary.v1+json"}
====
where *_consumer_group_* is a consumer group name, *_instance_name_* is a consumer instance name, and *_topic_* is a topic name.

.Sample Request (subscribing to binary topic "test" by consumer "my_instance" at consumer group "my_consumer_group")
----
{"id": "127", "method": "GET", "path": "/ws/consumers/my_consumer_group/instances/my_instance/topics/test", "accept": "application/vnd.kafka.binary.v1+json"}
----

.Sample Response
----
{"id": "127", "data": [{"key":null,"value":"SG9sYSBLYWZrYQ==","partition":0,"offset":0},{"key":null,"value":"S2Fma2E=","partition":0,"offset":1},{"key":null,"value":"S2Fma2E=","partition":0,"offset":2},{"key":null,"value":"S2Fma2E=","partition":0,"offset":3}]}
{"id": "127", "data": {"key":null,"value":"S2Fma2E=","partition":0,"offset":4}}
----


     - 3. Unsubscribe the topic

[caption="Format: "]
.unsubscribeTopic
====
{"id": "*_identifier_*", "method": "DELETE", "path": "/ws/consumers/*_consumer_group_*/instances/*_instance_name_*/topics/*_topic_*"}
====
where *_consumer_group_* is a consumer group name, *_instance_name_* is a consumer instance name, and *_topic_* is a topic name.

.Sample Request (unsubscribing from topic "test" by consumer "my_instance" at consumer group "my_consumer_group")
----
{"id": "128", "method": "DELETE", "path": "/ws/consumers/my_consumer_group/instances/my_instance/topics/test"}
----

     - 4. Destroy the consumer

[caption="Format: "]
.deleteGroup
====
{"id": "*_identifier_*", "method": "DELETE", "path": "/consumers/*_consumer_group_*/instances/*_instance_name_*"}
====
where *_consumer_group_* is a consumer group name and *_instance_name_* is a consumer instance name

.Sample Request (deleting consumer "my_instance" at consumer group "my_consumer_group")
----
{"id": "129", "method": "DELETE", "path": "/consumers/my_consumer_group/instances/my_instance"}
----


==== Produce and consume messages in JSON Mode

===== Producing Messages (JSON-Mode)

[caption="Format: "]
.produceJson
====
{"id": "*_identifier_*", "method": "POST", "path": "/topics/*_topic_*", "type": "application/vnd.kafka.json.v1+json",  "data": {"records": [{"value": *_json_message_*}]}}
====
where *_topic_* is a topic name and *_json_message_* is a json encoded string representing the content entity.

.Sample Request (publishing json message {"greeting": "hey"} to topic "jsontest")
----
{"id": "125", "method": "POST", "path": "/topics/jsontest", "type": "application/vnd.kafka.json.v1+json", "data": {"records": [{"value": {"greeting": "hey"}}]}}
----

.Sample Response
----
{"id": "125", "data": {"offsets":[{"partition":0,"offset":11,"error_code":null,"error":null}],"key_schema_id":null,"value_schema_id":null}}
----

.Sample Request (publishing json messages "foo" and {"greeting": "bye"} to topic "jsontest")
----
{"id": "126", "method": "POST", "path": "/topics/jsontest", "type": "application/vnd.kafka.json.v1+json",  "data": {"records": [{"value": "foo"}, {"value": {"greeting": "bye"}}]}}
----

.Sample Response
----
 {"id": "126", "data": {"offsets":[{"partition":0,"offset":12,"error_code":null,"error":null},{"partition":0,"offset":13,"error_code":null,"error":null}],"key_schema_id":null,"value_schema_id":null}}
----


===== Consuming Messages (JSON-Mode)

      
     - 1. Create a consumer (JSON-Mode)

[caption="Format: "]
.createGroup
====
{"id": "*_identifier_*", "method": "POST", "path": "/consumers/*_consumer_group_*", "type": "application/vnd.kafka.json.v1+json",  "data": {"id": "*_instance_name_*", "format": "json", "auto.offset.reset": "smallest"}}
====
where *_consumer_group_* is a consumer group name and *_instance_name_* is a consumer instance name.

.Sample Request (creating json consumer "my_json_instance" at consumer group "my_json_consumer_group")
----
{"id": "126", "method": "POST", "path": "/consumers/my_json_consumer_group", "type": "application/vnd.kafka.json.v1+json",  "data": {"id": "my_json_instance", "format": "json", "auto.offset.reset": "smallest"}}
----

.Sample Response
----
 {"id": "126", "data": {"instance_id":"my_json_instance","base_uri":"http://localhost:8082/consumers/my_json_consumer_group/instances/my_json_instance"}}
----

     - 2. Subscribe to the topic (JSON-Mode)

[caption="Format: "]
.subscribeTopicJson
====
{"id": "*_identifier_*", "method": "GET", "path": "/ws/consumers/*_consumer_group_*/instances/*_instance_name_*/topics/*_topic_*", "accept": "application/vnd.kafka.json.v1+json"}
====
where *_consumer_group_* is a consumer group name, *_instance_name_* is a consumer instance name, and *_topic_* is a topic name.

.Sample Request (subscribing json topic "jsontest" by consumer "my_json_instance" at consumer group "my_json_consumer_group")
----
{"id": "127", "method": "GET", "path": "/ws/consumers/my_json_consumer_group/instances/my_json_instance/topics/jsontest", "accept": "application/vnd.kafka.json.v1+json"}
----

.sample Response
----
{"id": "127", "data": [{"key":null,"value":{"greeting":"hey"},"partition":0,"offset":1},{"key":null,"value":{"greeting":"hey"},"partition":0,"offset":2},{"key":null,"value":{"greeting":"bye"},"partition":0,"offset":3}]}
{"id": "127", "data": {"key":null,"value":{"greeting":"bye"},"partition":0,"offset":4}}
----

     - 3. Unsubscribe from the topic

[caption="Format: "]
.unsubscribeTopic
====
{"id": "*_identifier_*", "method": "DELETE", "path": "/ws/consumers/*_consumer_group_*/instances/*_instance_name_*/topics/*_topic_*"}
====
where *_consumer_group_* is a consumer group name, *_instance_name_* is a consumer instance name, and *_topic_* is a topic name.

.Sample Request (unsubscribing from topic "jsontest" by consumer "my_json_instance" at consumer group "my_json_consumer_group")
----
{"id": "128", "method": "DELETE", "path": "/ws/consumers/my_json_consumer_group/instances/my_json_instance/topics/jsontest"}
----


     - 4. Destroy the consumer

[caption="Format: "]
.deleteGroup
====
{"id": "*_identifier_*", "method": "DELETE", "path": "/consumers/*_consumer_group_*/instances/*_instance_name_*"}
====
where *_consumer_group_* is a consumer group name and *_instance_name_* is a consumer instance name.

.Sample Request (deleting consumer "my_json_instance" at consumer group "my_json_consumer_group")
----
{"id": "129", "method": "DELETE", "path": "/consumers/my_json_consumer_group/instances/my_json_instance"}
----


==== References

- [1] http://docs.confluent.io/2.0.0/kafka-rest/docs/intro.html#produce-and-consume-binary-messages[http://docs.confluent.io/2.0.0/kafka-rest/docs/intro.html#produce-and-consume-binary-messages]
