= kafka-rest-atmosphere

This is a proxy gateway based on kafka-rest[1] (2.0.1) and atmosphere[2] (2.4.3) to transparently 
add a Websocket based transport binding to kafka-rest's HTTP REST proxy gateway. 
As a result, the provided services of kafka-rest can be invoked over HTTP or Websocket and possibly other
protocols supported by atmosphere. In addition, new services utilizing Websocket can also be supported
in the same gateway.

The advantage of using Websocket is its support of asynchronous duplex communication over a single socket. 
Messages can be sent and received asynchronously on a single connection. 
This advantage could be particularly utilized when the protocol gateway is specifically designed for a Websocket.

In contrast, this particular gateway uses a different approach, namely
using kafka-rest's existing REST services and transparently enabling those services to be invoked over Websocket
and other protocols such as Server-Side-Events (SSE) using atmosphere.
In addition, new consumer services are added to support the transport of messages continuously over the socket.
There are advantages and disadvantages in this approach. For more details, 
please refer to section Advantages and Disadvantages.

== Deployment

The shell scripts bin/kafka-rest-atmosphere-start and bin/kafka-rest-atmosphere-stop are
available in package's bin folder. They are based on kafka-rest's shell scripts and 
can be used to start or stop the standalone kafka-rest-atmosphere server, respectively.

== Using Websocket

=== Connecting

Use your websocket client to connect to ws://localhost:8082
For example, you can use the Echo demo at http://www.websocket.org/echo.html as your client and 
connect to the server at ws://localhost:8082/ and paste the appropriate JSON messages in its 
Message text field. There is also a node client based on atmosphere.js available
at package's link:https://github.com/elakito/kafka-rest-atmosphere/tree/master/src/test/resources/node[share/utils/node].


=== Invoking operations

Any of the REST operations that are supported by kafka-rest may be invoked over HTTP or Websocket.
When invoking an operation over Websocket, the message must be serialized in the Websocket binding
format using the following JSON format.

--------------------------------------
   {"id": "<identifier>", "method": "<method>", "path": "<path>", 
    "type": "<type_header>", "accept": "<accept_header>",
    "data": <content>}
--------------------------------------

where <identifier> represents an identifier to correlate the response to its original request,
<method> represents the request method, <path> represents the request path, <type_header> and <accept_header>
represent the optional content-type and accept headers, and <content> represents the optinal content entity.

For example, an HTTP request to list topics

--------------------------------------
   GET /topics HTTP/1.1
   Host: localhost:8082
   Accept: */*

--------------------------------------

will correspond to a JSON message of

--------------------------------------
   {"id": "...", "method": "GET", "path": "/topics"}
--------------------------------------

Similarly, an HTTP request to publish a message "Kafka" to topic "test"

--------------------------------------
    POST /topics/test HTTP/1.1
    Host: localhost:8082
    Accept: */*
    Content-Type: application/vnd.kafka.binary.v1+json
    Content-Length: 34
    
    {"records":[{"value":"S2Fma2E="}]}

--------------------------------------

will correspond to a JSON message of

--------------------------------------
    {"id": "...", "method": "POST", "path": "/topics/test", 
     "type": "application/vnd.kafka.binary.v1+json",
     "data": {"records":[{"value":"S2Fma2E="}]}}
--------------------------------------

For details and more samples, refer to kafka-rest-websocket-binding [3]. For available operations, 
refer to the kafka-rest documentation [4]


=== Additional operations supported for Websocket

Addtional operations are specifically included for the Websocket binding to allow a consumer to subscribe
to a topic and get messages pushed asynchronously over Websocket. This feature requires a modified version of 
kafka-rest [5].

To subscribe to a Binary topic

--------------------------------------
    {"id": "...", "method": "GET", 
     "path": "/ws/consumers/<consumer_group>/instances/<instance_name>/topics/<topic>", 
     "accept": "application/vnd.kafka.binary.v1+json"}
--------------------------------------

To subscribe to a JSON topic

--------------------------------------
    {"id": "...", "method": "GET", 
     "path": "/ws/consumers/<consumer_group>/instances/<instance_name>/topics/<topic>", 
     "accept": "application/vnd.kafka.json.v1+json"}
--------------------------------------

To unsubscribe from the topic

--------------------------------------
    {"id": "...", "method": "DELETE", 
     "path": "/ws/consumers/<consumer_group>/instances/<instance_name>/topics/<topic>"}
--------------------------------------

=== Advantages and Disadvantages

In the following, the advantages and disadvantages of this particular approach are described.

===== Advantages

- The client can use the same payload as used in kafka-rest's http proxy.
- The existing kafka-rest services can be reused directly and invoked over either http or Websocket
- The consumer specific subscription services are integrated to the existing kafka-rest's services so that
messages can be transferred to the subscribers asynchronously.
- The client can choose its preferred protocol based on its use cases.
- The same transport security setting can be reused for both protocols.
- atmosphere supports additional protocols such as SSE which can also be supported along with Websocket.

===== Disadvantages

- There is an overhead in extracting the actual payload from a message sent over Websocket and internally invoking the target REST service, in contrast to extracing the payload and internally invoking Kafka's client API directly.

== Using Other protocols

Currently, Server-Side-Events (SSE) is also supported to receive responses over a single connection that is kept open.

For HTTP, please refer to the documentation for kafka-rest [4].

=== References
- [1] link:https://github.com/confluentinc/kafka-rest[]

- [2] link:https://github.com/Atmosphere/atmosphere[]

- [3] link:kafka-rest-websocket-binding.adoc[]

- [4] link:http://docs.confluent.io/2.0.0/kafka-rest/docs/index.html[]

- [5] link:https://github.com/elakito/kafka-rest/tree/2.x-websocket[]
