= kafka-rest-atmosphere

This application is based on kafka-rest[1] (2.0.1) and use atmosphere[2] (2.4.3) to add a websocket based 
transport to kafka-rest's API. As a result, the provided services can be invoked over either HTTP or Websocket.

The advantage of using Websocket is its support of asynchronous duplex communication. Messages can be
posted and received asynchronously. This advantage can be particularly utilized when the communication protocol
is specifically designed for a Websocket.

In contrast, this particular application uses a different approach, namely
enabling kafka-rest's REST services to be invoked over Websocket. In addition, additional consumer services are added
to support the transport of messages continuously over the socket. Please refer to section Advantages and Disadvantages
below for more details regarding this aspect.


== Using Websocket

=== Connecting

Use your websocket client to connect to ws://localhost:8082
For example, you can use the Echo demo at http://www.websocket.org/echo.html as your client and 
connect to the server at ws://hostname:8082/ and paste the appropriate JSON messages in its 
Message text field.


=== Invoking operations

Any of the REST operations that are supported by kafka-rest may be invoked over HTTP or Websocket.
When invoking an operation over Websocket, the message must be serialized in the Websocket binding
format using the following JSON format.

--------------------------------------
   {"id": "<identifier>", "method": "<method>", "path": "<path>", 
    "type": "<type_header>", "accept": "<accept_header>",
    "data": <content>}
--------------------------------------

where <identifier> represents an identifier to correlate the response to its original request,
<method> represents the request method, <path> represents the request path, <type_header> and <accept_header>
represent the optional content-type and accept headers, and <content> represents the optinal content entity.

For example, an HTTP request to list topics

--------------------------------------
   GET /topics HTTP/1.1
   Host: localhost:8082
   Accept: */*

--------------------------------------

will correspond to a JSON message of

--------------------------------------
   {"id": "...", "method": "GET", "path": "/topics"}
--------------------------------------

Similarly, an HTTP request to publish a message "Kafka" to topic "test"

--------------------------------------
    POST /topics/test HTTP/1.1
    Host: localhost:8082
    Accept: */*
    Content-Type: application/vnd.kafka.binary.v1+json
    Content-Length: 34
    
    {"records":[{"value":"S2Fma2E="}]}

--------------------------------------

will correspond to a JSON message of

--------------------------------------
    {"id": "...", "method": "POST", "path": "/topics/test", 
     "type": "application/vnd.kafka.binary.v1+json",
     "data": {"records":[{"value":"S2Fma2E="}]}}
--------------------------------------

For details and more samples, refer to kafka-rest-websocket-binding [3]. For available operations, 
refer to the kafka-rest documentation [4]


=== Additional operations supported for Websocket

Addtional operations are specifically included for the Websocket binding to allow a consumer to subscribe
to a topic and get messages pushed asynchronously over Websocket.

To subscribe to a Binary topic

--------------------------------------
    {"id": "...", "method": "GET", 
     "path": "/ws/consumers/<consumer_group>/instances/<instance_name>/topics/<topic>", 
     "accept": "application/vnd.kafka.binary.v1+json"}
--------------------------------------

To subscribe to a JSON topic

--------------------------------------
    {"id": "...", "method": "GET", 
     "path": "/ws/consumers/<consumer_group>/instances/<instance_name>/topics/<topic>", 
     "accept": "application/vnd.kafka.json.v1+json"}
--------------------------------------

To unsubscribe from the topic

--------------------------------------
    {"id": "...", "method": "DELETE", 
     "path": "/ws/consumers/<consumer_group>/instances/<instance_name>/topics/<topic>"}
--------------------------------------

=== Advantages and Disadvantages

In the following, the advantages and disadvantages of this particular approach are described.

===== Advantages

- The client can use the same payload as used in kafka-rest's http proxy.
- The existing kafka-rest services can be reused directly and invoked over either http or Websocket
- The consumer specific subscription services are integrated to the existing kafka-rest's services so that
messages can be transferred to the subscribers asynchronously.
- The client can choose its preferred protocol based on its use cases.
- The same transport security setting can be reused for both protocols.

===== Disadvantages

- There is an overhead in extracting the actual payload from a message sent over Websocket and internally invoking the target REST service, in contrast to extracing the payload and internally invoking Kafka's client API directly.

=== References
- [1] link:https://github.com/confluentinc/kafka-rest[]

- [2] link:https://github.com/Atmosphere/atmosphere[]

- [3] link:kafka-rest-websocket-binding.adoc[]

- [4] link:http://docs.confluent.io/2.0.0/kafka-rest/docs/intro.html#produce-and-consume-binary-messages[]
